//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bludo
    {
        public Nullable<int> id_Bludo { get; set; }
        public string name_Bludo { get; set; }
        public Nullable<int> weight_Bludo { get; set; }
        public Nullable<int> price_Bludo { get; set; }
        public string category_Bludo { get; set; }
        public Nullable<int> time_Bludo { get; set; }
        public int id { get; set; }
    }
}
