//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class BludoInOrder
    {
        public Nullable<int> id_Bludo { get; set; }
        public Nullable<int> number_Bludo { get; set; }
        public Nullable<System.DateTime> ordertime { get; set; }
        public Nullable<int> id_Order { get; set; }
        public string status { get; set; }
        public int id { get; set; }
    }
}
