//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamProjectEntities6 : DbContext
    {
        public TeamProjectEntities6()
            : base("name=TeamProjectEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bludo> Bludo { get; set; }
        public DbSet<BludoInOrder> BludoInOrder { get; set; }
        public DbSet<OrderInTime> OrderInTime { get; set; }
        public DbSet<Table> Table { get; set; }
        public DbSet<Waiter> Waiter { get; set; }
    }
}
