//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiter
    {
        public Nullable<int> id_Waiter { get; set; }
        public string name_Waiter { get; set; }
        public string surname_Waiter { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id { get; set; }
    }
}
